services:
  - type: web
    name: blog-laravue-demo
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        value: ${RENDER_EXTERNAL_URL}
      - key: APP_KEY
        value: base64:Y7ozrhBK+221B8xjsv6N578BfexFlnCkve7T4pWyi+c=
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /app/database/database.sqlite
      - key: LOG_CHANNEL
        value: stderr
      - key: PORT
        value: 10000