services:
  - type: web
    name: blog-laravue-demo
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: APP_URL
        value: ${RENDER_EXTERNAL_URL}
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
      - key: PORT
        value: 10000
